config/routes.rb
Rails.application.routes.draw do
  scope "api" do
  resources :customer, only: [:index, :show, :create]
  resources :pharmacies
  resources :payments
  resources :invoices
  resources :order_items
  resources :orders
  resources :medication, only: [:index, :show, :create]
  end
  
  get "/api/current_user", to:"customer#current_user"
  post '/api/login', to: 'session#login'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/pharmacy.rb
class Pharmacy < ApplicationRecord
end

app/controllers/pharmacies_controller.rb
class PharmaciesController < ApplicationController
  before_action :set_pharmacy, only: %i[ show edit update destroy ]

  # GET /pharmacies or /pharmacies.json
  def index
    @pharmacies = Pharmacy.all
  end

  # GET /pharmacies/1 or /pharmacies/1.json
  def show
  end

  # GET /pharmacies/new
  def new
    @pharmacy = Pharmacy.new
  end

  # GET /pharmacies/1/edit
  def edit
  end

  # POST /pharmacies or /pharmacies.json
  def create
    @pharmacy = Pharmacy.new(pharmacy_params)

    respond_to do |format|
      if @pharmacy.save
        format.html { redirect_to pharmacy_url(@pharmacy), notice: "Pharmacy was successfully created." }
        format.json { render :show, status: :created, location: @pharmacy }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @pharmacy.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pharmacies/1 or /pharmacies/1.json
  def update
    respond_to do |format|
      if @pharmacy.update(pharmacy_params)
        format.html { redirect_to pharmacy_url(@pharmacy), notice: "Pharmacy was successfully updated." }
        format.json { render :show, status: :ok, location: @pharmacy }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @pharmacy.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pharmacies/1 or /pharmacies/1.json
  def destroy
    @pharmacy.destroy

    respond_to do |format|
      format.html { redirect_to pharmacies_url, notice: "Pharmacy was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pharmacy
      @pharmacy = Pharmacy.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def pharmacy_params
      params.fetch(:pharmacy, {})
    end
end

app/helpers/pharmacies_helper.rb
module PharmaciesHelper
end

app/views/pharmacies/_form.html.erb
<%= form_with(model: pharmacy) do |form| %>
  <% if pharmacy.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(pharmacy.errors.count, "error") %> prohibited this pharmacy from being saved:</h2>

      <ul>
        <% pharmacy.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/pharmacies/_pharmacy.html.erb
<div id="<%= dom_id pharmacy %>">
</div>

app/views/pharmacies/edit.html.erb
<h1>Editing pharmacy</h1>

<%= render "form", pharmacy: @pharmacy %>

<br>

<div>
  <%= link_to "Show this pharmacy", @pharmacy %> |
  <%= link_to "Back to pharmacies", pharmacies_path %>
</div>

app/views/pharmacies/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Pharmacies</h1>

<div id="pharmacies">
  <% @pharmacies.each do |pharmacy| %>
    <%= render pharmacy %>
    <p>
      <%= link_to "Show this pharmacy", pharmacy %>
    </p>
  <% end %>
</div>

<%= link_to "New pharmacy", new_pharmacy_path %>

app/views/pharmacies/new.html.erb
<h1>New pharmacy</h1>

<%= render "form", pharmacy: @pharmacy %>

<br>

<div>
  <%= link_to "Back to pharmacies", pharmacies_path %>
</div>

app/views/pharmacies/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @pharmacy %>

<div>
  <%= link_to "Edit this pharmacy", edit_pharmacy_path(@pharmacy) %> |
  <%= link_to "Back to pharmacies", pharmacies_path %>

  <%= button_to "Destroy this pharmacy", @pharmacy, method: :delete %>
</div>